// <auto-generated/>
// FSharp.Azure.Quantum - Global C# Extensions (.NET 10)
// This file makes extension methods automatically available for C# projects.
//
// These global usings are automatically included when you reference the FSharp.Azure.Quantum NuGet package.
// No manual 'using' statements needed in your C# code!

// Core namespace
global using FSharp.Azure.Quantum;

// Static helper class for creating problems with C# value tuples
// Examples: KnapsackProblem(), TspProblem(), MaxCutProblem()
global using static FSharp.Azure.Quantum.CSharpBuilders;

// Extension methods for F# list operations, Result types, and tuple conversions
// Examples: fsharpList.Count(), result.IsOk(), result.GetOkValue(), fsharpList.ToCSharpList()
global using static FSharp.Azure.Quantum.BuildersCSharpExtensions;

// Extension methods for quantum backends (async/await support)
// Examples: backend.ExecuteToStateTask(), backend.CheckSupportsOperation()
global using static FSharp.Azure.Quantum.QuantumBackendCSharpExtensions;

// Extension methods for model serialization (Task-based async)
global using static FSharp.Azure.Quantum.ModelSerializationCSharpExtensions;

// Extension methods for quantum chemistry (Task-based async)
global using static FSharp.Azure.Quantum.QuantumChemistryCSharpExtensions;

// Extension methods for SVM models (Task-based async)
global using static FSharp.Azure.Quantum.SVMModelSerializationCSharpExtensions;
